name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/e9b4486e5cb972cdb482690080dfcd70.png
    - assets/images/horarios1.jpg
    - assets/images/horarios2.jpg
    - assets/images/maps.png
    - assets/images/rectangl.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_3.png
    - assets/images/rectangle_4.png
    - assets/images/rectangle_5.png
    - assets/images/rectangle_6.png
    - assets/images/rectangle_7.png
    - assets/images/rectangle_9.png
    - assets/images/rectangle_10.png
    - assets/images/rectangle_11.png
    - assets/images/rectangle_13.png
    - assets/images/rectangle_15.png
    - assets/images/rectangle_16.png
    - assets/images/rectangle_18.png
    - assets/images/rectangle_20.jpeg
    - assets/images/rectangle_22.png
    - assets/images/rectangle_23.jpeg
