name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/rectangle_1.png
    - assets/images/rectangle_16.png
    - assets/vectors/vector_x2.svg
    - assets/vectors/vector_17_x2.svg
    - assets/vectors/clip_path_group_3_x2.svg
    - assets/vectors/vector_9_x2.svg
    - assets/vectors/clip_path_group_7_x2.svg
    - assets/vectors/ellipse_2_x2.svg
    - assets/vectors/vector_44_x2.svg
    - assets/vectors/clip_path_group_23_x2.svg
    - assets/vectors/clip_path_group_19_x2.svg
    - assets/vectors/clip_path_group_1_x2.svg
    - assets/vectors/clip_path_group_17_x2.svg
    - assets/vectors/vector_31_x2.svg
    - assets/vectors/clip_path_group_52_x2.svg
    - assets/images/rectangle_21.jpeg
    - assets/images/rectangle_4.jpeg
    - assets/images/rectangle_12.jpeg
    - assets/images/rectangle_14.jpeg
    - assets/images/rectangle_19.jpeg
    - assets/images/rectangle_17.jpeg
    - assets/images/rectangle_8.jpeg

    - assets/vectors/vector_2_x2.svg
    - assets/vectors/vector_53_x2.svg
    - assets/vectors/vector_8_x2.svg
    - assets/vectors/vector_39_x2.svg
    - assets/vectors/vector_45_x2.svg
    - assets/vectors/vector_38_x2.svg
    - assets/vectors/vector_35_x2.svg
    - assets/vectors/vector_6_x2.svg
    - assets/vectors/vector_14_x2.svg
    - assets/vectors/vector_29_x2.svg
    - assets/vectors/vector_49_x2.svg
    - assets/vectors/vector_13_x2.svg
    - assets/vectors/vector_4_x2.svg
    - assets/vectors/vector_18_x2.svg
    - assets/vectors/vector_22_x2.svg
    - assets/vectors/vector_54_x2.svg
    - assets/vectors/vector_26_x2.svg
    - assets/vectors/vector_16_x2.svg
    - assets/vectors/vector_12_x2.svg
    - assets/vectors/vector_51_x2.svg
    - assets/vectors/vector_34_x2.svg
    - assets/vectors/vector_21_x2.svg
    - assets/vectors/vector_27_x2.svg
    - assets/vectors/vector_25_x2.svg
    - assets/vectors/vector_33_x2.svg
    - assets/vectors/vector_32_x2.svg
    - assets/vectors/vector_23_x2.svg
    - assets/vectors/vector_56_x2.svg
    - assets/vectors/vector_11_x2.svg
    - assets/vectors/group_1_x2.svg
    - assets/vectors/vector_48_x2.svg
    - assets/vectors/vector_15_x2.svg
    - assets/vectors/vector_3_x2.svg
    - assets/vectors/vector_36_x2.svg
    - assets/vectors/vector_7_x2.svg
    - assets/vectors/vector_42_x2.svg
    - assets/vectors/vector_46_x2.svg
    - assets/vectors/vector_24_x2.svg
    - assets/vectors/vector_30_x2.svg
    - assets/vectors/group_x2.svg
    - assets/vectors/vector_47_x2.svg
    - assets/vectors/container_x2.svg
    - assets/vectors/vector_10_x2.svg
    - assets/vectors/vector_1_x2.svg
    - assets/vectors/vector_20_x2.svg
    - assets/vectors/vector_37_x2.svg
    - assets/vectors/vector_43_x2.svg
    - assets/vectors/vector_28_x2.svg
    - assets/vectors/vector_19_x2.svg
    - assets/vectors/vector_5_x2.svg
    - assets/vectors/container_1_x2.svg
    - assets/vectors/vector_40_x2.svg
    - assets/vectors/vector_55_x2.svg
    - assets/vectors/vector_52_x2.svg
    - assets/images/rectangle_15.png
    - assets/images/rectangle_9.png
    - assets/images/rectangle_7.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_18.png
    - assets/images/rectangle_11.png
    - assets/vectors/clip_path_group_14_x2.svg
    - assets/vectors/clip_path_group_41_x2.svg
    - assets/vectors/clip_path_group_38_x2.svg
    - assets/vectors/clip_path_group_33_x2.svg
    - assets/vectors/clip_path_group_2_x2.svg
    - assets/vectors/clip_path_group_4_x2.svg
    - assets/vectors/clip_path_group_13_x2.svg
    - assets/vectors/clip_path_group_20_x2.svg
    - assets/vectors/clip_path_group_47_x2.svg
    - assets/vectors/clip_path_group_6_x2.svg
    - assets/images/rectangle_9.png
    - assets/images/rectangle_18.png
    - assets/images/rectangle_15.png
    - assets/images/rectangle_11.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_7.png
    - assets/vectors/clip_path_group_12_x2.svg
    - assets/vectors/clip_path_group_25_x2.svg
    - assets/vectors/clip_path_group_27_x2.svg
    - assets/vectors/clip_path_group_30_x2.svg
    - assets/vectors/clip_path_group_51_x2.svg
    - assets/vectors/clip_path_group_36_x2.svg
    - assets/vectors/clip_path_group_11_x2.svg
    - assets/vectors/clip_path_group_31_x2.svg
    - assets/vectors/clip_path_group_50_x2.svg
    - assets/vectors/clip_path_group_42_x2.svg
    - assets/images/rectangle_11.png
    - assets/images/rectangle_15.png
    - assets/images/rectangle.png
    - assets/images/rectangle_6.png
    - assets/images/rectangle_10.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_7.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_18.png
    - assets/images/rectangle_4.png
    - assets/images/rectangle_13.png
    - assets/images/rectangle_9.png
    - assets/images/rectangle_3.png
    - assets/images/rectangle_20.jpeg
    - assets/images/rectangle_3.png
    - assets/images/maps.png
    - assets/vectors/clip_path_group_5_x2.svg
    - assets/vectors/clip_path_group_21_x2.svg
    - assets/vectors/clip_path_group_24_x2.svg
    - assets/vectors/clip_path_group_16_x2.svg
    - assets/vectors/clip_path_group_18_x2.svg
    - assets/vectors/clip_path_group_43_x2.svg
    - assets/vectors/vector_50_x2.svg
    - assets/vectors/clip_path_group_44_x2.svg
    - assets/vectors/clip_path_group_35_x2.svg
    - assets/vectors/clip_path_group_54_x2.svg
    - assets/vectors/clip_path_group_32_x2.svg
    - assets/vectors/clip_path_group_29_x2.svg
    - assets/vectors/clip_path_group_22_x2.svg
    - assets/vectors/vector_41_x2.svg
    - assets/vectors/clip_path_group_15_x2.svg
    - assets/vectors/clip_path_group_34_x2.svg
    - assets/vectors/clip_path_group_28_x2.svg
    - assets/vectors/clip_path_group_46_x2.svg
    - assets/vectors/clip_path_group_9_x2.svg
    - assets/vectors/clip_path_group_48_x2.svg
    - assets/vectors/clip_path_group_49_x2.svg
    - assets/vectors/clip_path_group_53_x2.svg
    - assets/vectors/clip_path_group_37_x2.svg
    - assets/vectors/clip_path_group_39_x2.svg
    - assets/images/rectangle_16.png
    - assets/images/rectangle_5.png
    - assets/images/rectangle_1.png
    - assets/vectors/clip_path_group_8_x2.svg
    - assets/vectors/clip_path_group_10_x2.svg
    - assets/vectors/clip_path_group_45_x2.svg
    - assets/vectors/clip_path_group_x2.svg
    - assets/vectors/clip_path_group_40_x2.svg
    - assets/vectors/clip_path_group_26_x2.svg
    - assets/images/rectangl.png
    - assets/images/e9b4486e5cb972cdb482690080dfcd70.png
    - assets/images/rectangle_22.png
    - assets/images/rectangle_23.jpeg
