name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/e9b4486e5cb972cdb482690080dfcd70.png
    - assets/images/horarios1.jpg
    - assets/images/horarios2.jpg
    - assets/images/maps.png
    - assets/images/rectangl.png
    - assets/images/rectangle.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_3.png
    - assets/images/rectangle_4.png
    - assets/images/rectangle_5.png
    - assets/images/rectangle_6.png
    - assets/images/rectangle_7.png
    - assets/images/rectangle_9.png
    - assets/images/rectangle_10.png
    - assets/images/rectangle_11.png
    - assets/images/rectangle_13.png
    - assets/images/rectangle_15.png
    - assets/images/rectangle_16.png
    - assets/images/rectangle_18.png
    - assets/images/rectangle_20.jpeg
    - assets/images/rectangle_22.png
    - assets/images/rectangle_23.jpeg
    - assets/images/box1/box1.png
    - assets/images/box1/box2.png
    - assets/images/box1/box3.png
    - assets/images/box1/box4.png
    - assets/images/box1/box5.png
    - assets/images/box1/box6.png
    - assets/images/box1/box7.png
    - assets/images/box1/box8.png
    - assets/images/fut/fut1.png
    - assets/images/fut/fut2.png
    - assets/images/fut/fut3.png
    - assets/images/fut/fut4.png
    - assets/images/fut/fut5.png
    - assets/images/fut/fut6.png
    - assets/images/fut/fut7.png
    - assets/images/fut/fut8.png
    - assets/images/fut/fut9.png
    - assets/images/fut/fut10.png
    - assets/images/luchas/luch1.png
    - assets/images/luchas/luch2.png
    - assets/images/luchas/luch3.png
    - assets/images/luchas/luch4.png
    - assets/images/luchas/luch5.png
    - assets/images/estre/estre1.png
    - assets/images/estre/estre2.png
    - assets/images/estre/estre3.png
    - assets/images/estre/estre4.png
    - assets/images/estre/estre5.png
    - assets/images/estre/estre6.png
    - assets/images/estre/estre7.png
    - assets/images/estre/estre8.png
    - assets/images/horarios1.jpg
    - assets/images/horarios2.jpg
